#:schema https://github.com/YunoHost/apps/raw/master/schemas/config_panel.v1.schema.json

version = "1.0"

[main]
name.en = "Main configuration"
name.fr = "Configuration principale"

    [main.server_mode]
    name.en = "Server mode"
    name.fr = "Mode serveur"

        [main.server_mode.archives_paths]
        ask.en = "Mastodon archive(s) to display"
        ask.fr = "Archive(s) Mastodon à afficher"
        type = "text"
        help.en = "List one path to uncompressed Mastodon archive directory per line.\nPath can also point to external servers provided CORS headers are enabled."
        help.fr = "Indiquez un chemin vers un dossier contenant une archive décompressée de Mastodon par ligne.\nLes chemins peuvent pointer vers des serveurs externes pourvu que les en-têtes CORS soient activées."
