packaging_format = 2

id = "marl"
name = "Mastodon Archive Reader Lite (MARL)"
description.en = "A lightweight single-page app to explore the contents of your Mastodon archive file"
description.fr = "Une application légère tenant sur une page pour explorer le contenu de votre fichier d'archive Mastodon"

version = "1.0~ynh1"

maintainers = ["oleole39"]

[upstream]
license = "Apache-2.0"
demo = "https://s427.github.io/MARL"
userdoc = "https://github.com/s427/MARL?tab=readme-ov-file#usage"
code = "https://github.com/s427/MARL"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = "not_relevant"
sso = "not_relevant"

disk = "10M"
ram.build = "0M"
ram.runtime = "0M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/marl"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/s427/MARL/archive/refs/tags/v1.0.tar.gz"
        sha256 = "9428bc4cd43a8261e8e22ad5afb216c1287111c3f9a135b447e505f569b27333"
        format = "tar.gz"
        extract = true
        in_subdir = true
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.ports]
