#!/bin/bash
# In simple cases, you don't need a config script.

# With a simple config_panel.toml, you can write in the app settings, in the
# upstream config file or replace complete files (logo ...) and restart services.

# The config scripts allows you to go further, to handle specific cases
# (validation of several interdependent fields, specific getter/setter for a value,
# display dynamic informations or choices, pre-loading of config type .cube... ).

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

ynh_abort_if_errors

#=================================================
# RETRIEVE ARGUMENTS
#=================================================

install_dir=$(ynh_app_setting_get --key=install_dir)

#=================================================
# SPECIFIC GETTERS FOR TOML SHORT KEY
#=================================================

get__archives_paths() {
    local servers
    # Get servers list stored in $install_dir/js/config.js
    servers=($(sed -n '/^const servers/{:start /\];/!{N;b start};/^const servers = \[.*\];/p}' $install_dir/js/config.js | grep -oE '"[^"]+"' | sed 's/"//g')) # array
    if [ ${#servers[@]} = 0 ]; then
        echo YNH_NULL
    else
        echo "$servers"
    fi
}

#=================================================
# SPECIFIC SETTERS FOR TOML SHORT KEYS
#=================================================

set__archives_paths() {
    if [ -n $archives_paths ]; then
        echo "const servers = [" > $install_dir/js/config.js # overwrite file if it already exists
        while IFS= read -r server_path; do
            echo "  \"$(echo $server_path | tr -d ' ')\"," >> $install_dir/js/config.js
        done <<< "$archives_paths"
        echo "];" >> $install_dir/js/config.js
    else 
        rm $install_dir/js/config.js
    fi
    
    # We do not use ynh_app_setting_set (nor ynh_add_config) because config.js is not created by default at install (cf. https://github.com/s427/MARL/blob/main/dist/js/config.default.js) and thus should not be overwritten by the upgrade script.
}

#=================================================
ynh_app_config_run "$1"
