#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================


source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

# Settings are written both in app's settings.yml and in $install_dir/js/config.js via a custom setter (cf. app scripts/config). They are read from settings.yml only.
# Variables names initialized below are used as template tags to populate config.js entries during `ynh_config_add` command below.
archives_paths=""
lang="\"auto\""
theme="\"auto\""
sort_asc=true
page_size=10
combine_panels=false
default_panel="\"actor\""
simplify_posts_display=false
images_compact_layout=false
hide_no_alt_text_notice=false
loop_gifs=true
show_actor_json=false
show_posts_json=false
app_title="\"Mastodon Archive Reader Lite - MARL\""

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

temp_dir=$(mktemp -d)
ynh_setup_source --dest_dir="$temp_dir"
mv $temp_dir/dist/* $install_dir #keep only the content of `dist` folder
ynh_safe_rm $temp_dir

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template="config.js" --destination="$install_dir/js/config.js"

# FIXME: this should be handled by the core in the future
chmod 644 "$install_dir/js/config.js"
chown "$app:$app" "$install_dir/js/config.js"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_config_add_nginx

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
