#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

temp_dir=$(mktemp -d)
ynh_setup_source --dest_dir="$temp_dir"
mv $temp_dir/dist/* $install_dir #keep only the content of `dist` folder
ynh_safe_rm $temp_dir

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app ..."

ynh_config_add_nginx

if ynh_in_ci_tests;
then
    # create config file for CI so that it doesn't fail
    echo "const servers = [];" > $install_dir/js/config.js
fi

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Installation of $app completed"
