#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_safe_rm $install_dir
mkdir -p $install_dir
temp_dir=$(mktemp -d)
ynh_setup_source --dest_dir="$temp_dir"
mv "$temp_dir/dist/*" "$install_dir" #keep only the content of `dist` folder
ynh_safe_rm $temp_dir

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Upgrade of $app completed"
