#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_safe_rm $install_dir
mkdir -p $install_dir

temp_dir=$(mktemp -d)
ynh_setup_source --dest_dir="$temp_dir"
mv $temp_dir/dist/* $install_dir #keep only the content of `dist` folder
ynh_safe_rm $temp_dir
mv $install_dir/js/config.default.js $install_dir/js/config.js

chown -R "$app:www-data" "$install_dir"

#=================================================
# REAPPLY SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

if ynh_in_ci_tests;
then
    # create config file for CI so that it doesn't fail
    echo "const servers = [];" > $install_dir/js/config.js
fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
